### ISSUE TITLE
Feature: support selecting an architecture type when building an image

### ISSUE THREAD

**Issue by willzhang** [labring-actions/cluster-image#1072]
Longhorn v1.7.1 build failed.

```
Error: failed to save images: save image longhornio/openshift-origin-oauth-proxy:4.15: choosing an image from manifest list docker://longhornio/openshift-origin-oauth-proxy:4.15: no image found in manifest list for architecture arm64, variant "", OS linux
```

![image](https://github.com/user-attachments/assets/0229b976-3edd-49c0-a4ca-87a5df3c16fb)

There have no arm image
![image](https://github.com/user-attachments/assets/ef52bd9e-2396-4716-937b-d6e132331d76)

should support 
```
/imagebuild_apps longhorn v1.7.1 amd64
```

**Comment by cuisongliu** [comment]
<img width="450" alt="image" src="https://github.com/user-attachments/assets/2c2bbb58-25b1-44a4-a247-221810f03d74" />
可以支持单架构编译
