### ISSUE TITLE
【Auto-build】terminal

### ISSUE THREAD

**Issue by cuisongliu** [labring-actions/cluster-image#331]
```
Usage:
   /imagebuild_dockerimages appName appVersion
Available Args:
   appName:  current app dir
   appVersion: current app version
   buildArgs:  build args, split by ','

Example:
   /imagebuild_dockerimages helm v3.8.2 Key1=Value,Key2=Value2
```

**Comment by cuisongliu** [comment]
/imagebuild_dockerimages terminal 1.19.4 kubeVersion=1.24.4;ttydVersion=1.6.3

**Comment by cuisongliu** [comment]
/imagebuild_dockerimages terminal 1.19.4 kubeVersion=1.24.4;ttydVersion=1.6.3

**Comment by cuisongliu** [comment]
/imagebuild_dockerimages terminal 1.19.4 kubeVersion=1.24.4;ttydVersion=1.6.3

**Comment by cuisongliu** [comment]
/imagebuild_dockerimages terminal 1.19.4 kubeVersion=1.24.4;ttydVersion=1.6.3

**Comment by cuisongliu** [comment]
/imagebuild_dockerimages terminal 1.19.4 kubeVersion=1.24.4;ttydVersion=1.6.3

**Comment by cuisongliu** [comment]
/imagebuild_dockerimages terminal 1.19.4 kubeVersion=1.24.4;ttydVersion=1.6.3

**Comment by cuisongliu** [comment]
/imagebuild_dockerimages terminal 1.19.4 kubeVersion=1.24.4;ttydVersion=1.6.3

**Comment by cuisongliu** [comment]
/imagebuild_dockerimages terminal 1.19.4 kubeVersion=1.24.4;ttydVersion=1.6.3

**Comment by cuisongliu** [comment]
/imagebuild_dockerimages terminal 1.19.4 kubeVersion=1.24.4;ttydVersion=1.6.3

**Comment by cuisongliu** [comment]
/imagebuild_dockerimages terminal 1.19.4 kubeVersion=1.24.4;ttydVersion=1.6.3

**Comment by cuisongliu** [comment]
/imagebuild_dockerimages terminal 1.19.4 kubeVersion=1.24.4,ttydVersion=1.6.3,goVersion=1.20.1

**Comment by cuisongliu** [comment]
/imagebuild_dockerimages terminal 1.20.1-1.24.4 kubeVersion=1.24.4,ttydVersion=1.6.3,goVersion=1.20.1

**Comment by cuisongliu** [comment]
/imagebuild_dockerimages terminal 1.20.1-1.24.4 kubeVersion=1.24.4,ttydVersion=1.6.3,goVersion=1.20.1

**Comment by cuisongliu** [comment]
/imagebuild_dockerimages terminal 1.20.1-1.24.4 kubeVersion=1.24.4,ttydVersion=1.6.3,goVersion=1.20.1

**Comment by cuisongliu** [comment]
/imagebuild_dockerimages terminal 1.19.4 kubeVersion=1.24.4,ttydVersion=1.6.3,goVersion=1.19.4

**Comment by zzjin** [comment]
/imagebuild_dockerimages terminal 1.20.3 kubeVersion=1.25.6,ttydVersion=1.7.3,goVersion=1.20.3

**Comment by cuisongliu** [comment]
/imagebuild_dockerimages terminal 1.20.3 kubeVersion=1.25.6,ttydVersion=1.7.3,goVersion=1.20.3

**Comment by cuisongliu** [comment]
/imagebuild_dockerimages terminal 1.20.3 kubeVersion=1.25.6,ttydVersion=1.7.3,goVersion=1.20.3

**Comment by cuisongliu** [comment]
/imagebuild_dockerimages terminal 1.20.3 kubeVersion=1.25.6,ttydVersion=1.7.3,goVersion=1.20.3

**Comment by cuisongliu** [comment]
/imagebuild_dockerimages terminal 1.20.3 kubeVersion=1.25.6,ttydVersion=1.7.3,goVersion=1.20.3

**Comment by cuisongliu** [comment]
/imagebuild_dockerimages terminal 1.20.3 kubeVersion=1.25.6,ttydVersion=1.7.3,goVersion=1.20.3

**Comment by cuisongliu** [comment]
/imagebuild_dockerimages terminal 1.20.3 kubeVersion=1.25.6,ttydVersion=1.7.3,goVersion=1.20.3

**Comment by zzjin** [comment]
/imagebuild_dockerimages terminal 1.20.3 kubeVersion=1.25.6,ttydVersion=1.7.3,goVersion=1.20.3

**Comment by zzjin** [comment]
/imagebuild_dockerimages terminal 1.20.3 kubeVersion=1.25.6,ttydVersion=1.7.3,goVersion=1.20.3

**Comment by zzjin** [comment]
/imagebuild_dockerimages terminal 1.20.4 kubeVersion=1.25.6,ttydVersion=1.7.3,goVersion=1.20.4

**Comment by zzjin** [comment]
/imagebuild_dockerimages terminal 1.20.4-2 kubeVersion=1.25.6,ttydVersion=1.7.3,goVersion=1.20.4

**Comment by zzjin** [comment]
/imagebuild_dockerimages terminal 1.20.4-3 kubeVersion=1.25.6,ttydVersion=1.7.3,goVersion=1.20.4

**Comment by zzjin** [comment]
/imagebuild_dockerimages terminal 1.20.4-3 kubeVersion=1.25.6,ttydVersion=1.7.3,goVersion=1.20.4

**Comment by zzjin** [comment]
/imagebuild_dockerimages terminal 1.20.4-4 kubeVersion=1.25.6,ttydVersion=1.7.3,goVersion=1.20.4

**Comment by lingdie** [comment]
/imagebuild_dockerimages terminal 1.20.4-5 kubeVersion=1.25.6,ttydVersion=1.7.3,goVersion=1.20.4

**Comment by lingdie** [comment]
/imagebuild_dockerimages terminal 1.20.4-6 kubeVersion=1.25.6,ttydVersion=1.7.3,goVersion=1.20.4

**Comment by lingdie** [comment]
/imagebuild_dockerimages terminal 1.20.4-7 kubeVersion=1.25.6,ttydVersion=1.7.3,goVersion=1.20.4

**Comment by lingdie** [comment]
/imagebuild_dockerimages terminal 1.20.4-7 kubeVersion=1.25.6,ttydVersion=1.7.3,goVersion=1.20.4

**Comment by lingdie** [comment]
/imagebuild_dockerimages terminal 1.20.4-8 
kubeVersion=1.25.6,ttydVersion=1.7.3,goVersion=1.20.4

**Comment by lingdie** [comment]
/imagebuild_dockerimages terminal 1.20.4-8 kubeVersion=1.25.6,ttydVersion=1.7.3,goVersion=1.20.4

**Comment by lingdie** [comment]
/imagebuild_dockerimages terminal 1.20.4-8 kubeVersion=1.25.6,ttydVersion=1.7.3,goVersion=1.20.4

**Comment by lingdie** [comment]
/imagebuild_dockerimages terminal 1.20.4-9 kubeVersion=1.25.6,ttydVersion=1.7.3,goVersion=1.20.4
