### ISSUE TITLE
kubeblock v0.8.2 deploy eroor.

### ISSUE THREAD

**Issue by lingdie** [labring-actions/cluster-image#886]
sealos run labring/kubernetes:v1.27.11 labring/helm:v3.12.0 labring/cilium:v1.12.14
sealos run labring/kubeblocks:v0.8.2

![image](https://github.com/labring-actions/cluster-image/assets/56745951/91e42041-c43c-4e99-9bff-0fa369cc9557)

**Comment by JashBook** [comment]
Please install KubeBlocks crds before deploying KubeBlocks
```
wget https://github.com/apecloud/kubeblocks/releases/download/v0.8.2/kubeblocks_crds.yaml
kubectl create -f kubeblocks_crds.yaml
```
