### ISSUE TITLE
可以使用cluster-image 离线构建指定版本的kubernetes镜像供sealos run使用吗 

### ISSUE THREAD

**Issue by ricardolrl** [labring-actions/cluster-image#974]
可以使用cluster-image 离线构建指定版本的kubernetes镜像供sealos run使用吗

**Comment by ricardolrl** [comment]
使用runtime的kubernetes.sh进行离线构建吗 怎么替换为私有仓库的k8s相关组件镜像 以及所需要的二进制呢

**Comment by ricardolrl** [comment]
我将labring/kubernetes:v1.26.15的镜像mount至本地后 根据Kubefile重新构建镜像 可以构建成功 但是sealos run的时候会出现该错误 Error: can't apply application type images only since RootFS type image is not applied yet

**Comment by cuisongliu** [comment]
> 使用runtime的kubernetes.sh进行离线构建吗 怎么替换为私有仓库的k8s相关组件镜像 以及所需要的二进制呢

这个是image-cri-shim做的，只要镜像仓库有镜像就可以替换。

**Comment by cuisongliu** [comment]
> 我将labring/kubernetes:v1.26.15的镜像mount至本地后 根据Kubefile重新构建镜像 可以构建成功 但是sealos run的时候会出现该错误 Error: can't apply application type images only since RootFS type image is not applied yet

看一下你的Kubefile

**Comment by ricardolrl** [comment]
FROM ghcr.io/labring-actions/cache:kubernetes-v1.27.7-amd64
MAINTAINER sealos
LABEL init="init-cri.sh \$registryDomain \$registryPort && bash init.sh" \
      clean="clean.sh && bash clean-cri.sh \$criData" \
      check="check.sh \$registryData" \
      init-registry="init-registry.sh \$registryData \$registryConfig" \
      clean-registry="clean-registry.sh \$registryData \$registryConfig" \
      vip="\$defaultVIP"
ENV criData=/var/lib/containerd \
    registryData=/var/lib/registry \
    registryConfig=/etc/registry \
    registryDomain=sealos.hub \
    registryPort=5000 \
    registryUsername=admin \
    registryPassword=passw0rd \
    disableApparmor=false \
    SEALOS_SYS_CRI_ENDPOINT=/var/run/containerd/containerd.sock \
    SEALOS_SYS_IMAGE_ENDPOINT=/var/run/image-cri-shim.sock
COPY . .

这是mount下来后目录里自带的

**Comment by ricardolrl** [comment]
> > 使用runtime的kubernetes.sh进行离线构建吗 怎么替换为私有仓库的k8s相关组件镜像 以及所需要的二进制呢
> 
> 这个是image-cri-shim做的，只要镜像仓库有镜像就可以替换。



> > 使用runtime的kubernetes.sh进行离线构建吗 怎么替换为私有仓库的k8s相关组件镜像 以及所需要的二进制呢
> 
> 这个是image-cri-shim做的，只要镜像仓库有镜像就可以替换。
这个没有看懂具体步骤
